Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text.Json.Nodes;
using System.Text;
using TemporalBox.Interfaces;
using TemporalBox.Models;

namespace TemporalBox.Controllers
{
    public class CartController : Controller
    {
        private readonly ICart _cart;
        public CartController(ICart cart)
        {
            _cart = cart;
        }
        public async Task<IActionResult> CartIndex(CartItem cartItem)
        {
            if (cartItem.ProductId != 0 && !string.IsNullOrEmpty(cartItem.CartId))
            {
                cartItem.Quantity = 1;
                //adding cartItem
                var data = await _cart.addToCart(cartItem);
            }
            else if (!string.IsNullOrEmpty(cartItem.CartId))
            {
                //getting cart list
                var CartList = await _cart.GetCartItem(cartItem.CartId);
                return View(CartList);
            }

            cartItem.CartId = GlobalVariable.Email;
            var cartList = await _cart.GetCartItem(cartItem.CartId);

            if(cartList.Count!=0)
            {

                return View(cartList);
            }
            else
            {
                return View();
            }
        }

        [HttpPost]
        public async void UpdateCart(int itemId , int quantity ,decimal totalPrice)
        {
            var Client = new HttpClient();
            if (itemId != 0 && quantity != 0)
            {
                var apiUrl = "https://localhost:44373/api/Cart/UpdateCart";
                var parameters = new CartItem { ItemId = itemId, Quantity = quantity , Price=totalPrice };
                var jsonPayload = JsonConvert.SerializeObject(parameters);
                var content = new StringContent(jsonPayload, Encoding.UTF8, "application/json");
                var response = await Client.PutAsync(apiUrl, content);
            }
        }




    }

      
    }

Controllers/ProductViewController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using System.Text;
using TemporalBox.Interfaces;
using TemporalBox.Models;
using TemporalBox.Services;


namespace TemporalBox.Controllers
{
    public class ProductViewController : Controller
     {
        private readonly IWebHostEnvironment _webHost;
        private readonly IProducts _products;
  

        public ProductViewController(IWebHostEnvironment webHost, IProducts products)
        {
            _webHost = webHost;
            _products = products;
         
        }

        public IActionResult AddProduct()
        {
            return View();
        }

        
        public async Task<IActionResult> ShowProducts(Paging page )
        {
            var data = await  _products.GetProducts(page);
            GlobalVariable.CurrentPage = data.Paging.currentPage;
            GlobalVariable.PageCount = data.Paging.pageCount;

            var viewData = new PagedProductData
            {
                PagedData = data.PagedData,
                Paging = data.Paging
            };
           

            return View(viewData);

        }

        //partial View Method for product list
        public async Task <PartialViewResult> _ProductList(Paging paging)
        {
            var data = await _products.GetProducts(paging);

            var viewData = new PagedProductData
            {
                PagedData = data.PagedData,
                Paging = data.Paging
            };

            return PartialView(viewData);
        }

        //adding method for product detail

        public async Task<IActionResult> ProductDetail(int id)
        {
            var data = await _products.GetProductById(id);
            return View(data);
        }

        //adding filter to product list
        public async Task<PartialViewResult> FilterProducts(Paging paging)
        {
            if (paging.min != 0 || paging.max != 0 ) { 
              var data = await _products.FilterProducts(paging);
            
                var viewData = new PagedProductData
                {
                    PagedData = data.PagedData,
                    Paging = data.Paging
                };

                return PartialView("_ProductList", viewData);

            }
            else
            {
                return PartialView("_ProductList");
            }
        }

        [HttpPost]
        [ActionName("AddingProduct")]
        public async Task<IActionResult> AddingProduct(Product product)
        {
            var data = await _products.AddingProduct(product);
            return RedirectToAction("AddProduct");      
        }


        public async Task<IActionResult> EditProduct(int id)
        {
            var data = await _products.GetProductById(id);
            return View(data);
        }

        public async Task<IActionResult> UpdateProduct(Product product)
        {
            var data = await _products.UpdateProduct(product);
            return RedirectToAction("ShowProducts");


        }

        public async Task<IActionResult> DeleteProduct(int id )
        {             
            await _products.DeleteProductImage(id);
            return RedirectToAction("ShowProducts");

        }
    }
}

Controllers/SharedController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Net.Http;
using System.Net.Http.Headers;
using TemporalBox.Models;
using static System.Net.WebRequestMethods;

namespace TemporalBox.Controllers
{
    
    public class SharedController : Controller
    {
        private readonly HttpClient _httpClient;
        private readonly IConfiguration _configuration;
        public SharedController(HttpClient httpClient, IConfiguration configuration)
        {

            _httpClient = httpClient;
            _configuration = configuration;
        }


        public IActionResult Add()
        {
            return View();
        }

        public async Task<IActionResult> AllCategories()
        {

            var Client = new HttpClient();
            var apiUrl = $"{_configuration.GetSection("AccessUrl").Value}/Category/GetAllCategory";
            var token = GlobalVariable.Token;
            Client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
            var response = await Client.GetAsync(apiUrl);

            var data = JsonConvert.DeserializeObject<List<Categories>>(await response.Content.ReadAsStringAsync());

            return View(data);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var Clients = new HttpClient();
            var apiUrl = $"{_configuration.GetSection("AccessUrl").Value}/Category/GetCategory?id={id}";
            var response = await Clients.GetAsync(apiUrl);
            var data = JsonConvert.DeserializeObject<Categories>(await response.Content.ReadAsStringAsync());
            var dataList = new List<Categories> { data };


            return View(dataList);
        }

        public async Task<IActionResult> EditSubCategory(int id )
        {
            var Client = new HttpClient();
            var apiUrl = $"{_configuration.GetSection("AccessUrl").Value}/Category/GetSubCategoryWithId?id={id}";
            var response = await Client.GetAsync(apiUrl);
            var data=  JsonConvert.DeserializeObject<List<SubCategory>>(await response.Content.ReadAsStringAsync());
           
            ViewBag.subCategory = data;

            return View(data);
        }


        public async Task<IActionResult> GetSubCategory(int id)
        {
            var Client = new HttpClient();
            var apiUrl = $"{_configuration.GetSection("AccessUrl").Value}/Category/GetSubCategory?id={id}";
            var response = await Client.GetAsync(apiUrl);

            var data = JsonConvert.DeserializeObject<List<SubCategory>>(await response.Content.ReadAsStringAsync());
            ViewBag.SubcategoryList = data;
            return View(data);
        }

        public IActionResult AddCategory()
        {
            return View();
        }

      
    }
}

Views/Shared/Add.cshtml
@using Newtonsoft.Json
@using System.Net.Http.Headers
@{


    var Client = new HttpClient();
    var apiUrl = "https://localhost:44373/api/Category/GetAllCategory";
    var token = GlobalVariable.Token;
    Client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
    var response = await Client.GetAsync(apiUrl);
    var data = JsonConvert.DeserializeObject<List<Categories>>(await response.Content.ReadAsStringAsync());

}

<form method="post" id="AddForm">
    <div class="form-group">
        <label for="categoryName">Category Name</label>
        @* <input type="text" class="form-control" name="categoryName" placeholder="Enter Category Name"> *@
        <select class=" form-control cat_list">
            @{
                foreach (var item in data)
                {
                        <option class="cat_id" id="@item.CategoryId" value="@item.CategoryId">@item.CategoryName</option>
                }
            }

        </select>
    </div>
    <div class="form-group">
        <label for="subCategoryName">Subcategory Name</label>
        <input type="text" id="subCategory" class="form-control subCategory" name="subCategoryName" placeholder="Enter Subcategory Name">
    </div>
    <button type="submit" class="btn btn-primary save_subcategory">Submit</button>
</form>


<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>


<script>
    $(".save_subcategory").click(function () {
        debugger;
      
        var catId = $(".cat_list").find(":selected").val();
        var subcategoryName = $(".subCategory").val();

        $.ajax({
            type: "POST",
            url: `https://localhost:44373/api/Category/AddSubcategory?categoryId=${catId}&subCategoryName=${subcategoryName}`,
            
            
            success: function (response) {
                window.location.href = "/Shared/Add"
      

            },
            error: function (xhr, textStatus, errorThrown) {
                
            }
        })
    })
</script>


@* <script>
    $(document).ready(function () {
        $("#AddForm").submit(function (event) {
            event.preventDefault();
            var formData = {
                categoryName: $("input[name='categoryName']").val(),
                subCategoryList: [
                    {
                        subCategoryName: $("input[name= 'subCategoryName']").val()
                    }
                ]
            }
            console.log(formData);
         
            $.ajax({
                type: "POST",
                url: "https://localhost:44373/api/Category/AddCategory",
                data: JSON.stringify(formData),
                contentType: "application/json",
                success: function (response) {
                    if (response) {
                        window.location.href = "/Shared/Add";
                        alert("Added Successfully");
                    }

                },
                error: function (xhr, textStatus, errorThrown) {
                    console.log(xhr.responseText);
                }

            });
        });
    });



</script> *@

Views/Shared/AddCategory.cshtml
<form >
    <div class="form-group">
        <label for="categoryName">Category Name</label>
         <input type="text" class="form-control cat_field" placeholder="Enter Category Name">        
    </div>
    <input type="submit" class="btn btn-primary save_category" >
</form>
<script src="~/lib/jquery/dist/jquery.js"></script>
<script>
    $(".save_category").click(function () {
        debugger;

        var catname = $(".cat_field").val();
        

        $.ajax({
            
            type: "POST",
            url: `https://localhost:44373/api/Category/AddCategory?category=${catname}`,

            success: function (response) {
                window.location.href = "/Home/Index"
            },
            error: function (xhr, textStatus, errorThrown) {

            }
        })
    })
</script>

Views/Shared/AllCategories.cshtml
@model List<Categories>

<h1> All Category Names</h1>

<table class="table table-striped">
    <thead>
        <tr>
            AllCategories
            <th scope="col">Category Name</th>
            <th scope="col">Action Method</th>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
            <tr>
                <td>@item.CategoryName </td>
                <td>
                    <a class="btn btn-primary" asp-route-id="@item.CategoryId" role="button" asp-controller="Shared" asp-action="Edit">Edit</a>
                    <button type="button" cat-id="@item.CategoryId" class="btn btn-secondary delete">Delete</button>
                    <a class="btn btn-primary" id="@item.CategoryId" asp-route-id="@item.CategoryId" role="button" asp-controller="Shared" asp-action="GetSubCategory">SubCategory</a>
                   @*  @foreach (var sub in item.SubCategoryList)
                    {

                        <a class="btn btn-primary" asp-route-id="@sub.SubCategoryId" role="button" asp-controller="Shared" asp-action="EditSubCategory">Edit SubCategory Name</a>


                    } *@


                </td>
            </tr>

        }

    </tbody>

</table>


    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="~/js/index.js"></script>

Views/Shared/Category.cshtml
@model List<Categories>

<h1>Your Data</h1>
<h1>lorem2 sdvsdv cakvbka</h1>


<ul>
    @foreach (var item in Model)
    {
        <li>@item.CategoryId - @item.CategoryName</li>

    }
</ul>

Views/Shared/Edit.cshtml
@model List<Categories>


<form method="post" id="EditCategory">
    @if (Model != null){
    <div class="form-group">
        <label for="categoryName">Category Name</label>
        <input type="text" id="@Model[0].CategoryId" class="form-control input" name="@Model[0].CategoryName" value="@Model[0].CategoryName" />
    </div>
    }
    <button type="submit" class="btn btn-primary updateCategory">Submit</button>
</form>


<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>


<script>
    $(".updateCategory").click(function () {
        debugger;

        var catId = $(".input").attr("id");
        var categoryName = $(".input").val();
        console.log(categoryName);
        $.ajax({
            type: "PUT",
            url: `https://localhost:44373/api/Category/UpdateCategory?Id=${catId}&CategoryName=${categoryName}`,


            success: function (response) {
                window.location.href = "/Shared/AllCategories";

            },
            error: function (xhr, textStatus, errorThrown) {

            }
        })
    })
</script>

Views/Shared/EditSubCategory.cshtml
@model List<SubCategory>

<h1>This is sub Category</h1>
@if (Model != null && Model.Count > 0)
{
    <form method="post">
     
            <div class="form-group">
                <label asp-for="@Model[0].SubCategoryName">SubCategory Name</label>
                <input asp-for="@Model[0].SubCategoryName" class="SubCat" subId="@Model[0].SubCategoryId" value="@Model[0].SubCategoryName" />
                <input type="hidden" asp-for="@Model[0].SubCategoryId" />
            </div>
        
        <button type="submit" class="btn btn-primary EditSub">Submit</button>
    </form>
}
else
{
    <p>No data available</p>
}


<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<script>
    $(document).ready(function () {


        $(".EditSub").click(function () {
            var subCatId = $(".subCat").attr("subId");
            var subCatName = $(".subCat").val();
            console.log(subCatId);
            console.log(subCatName);
            debugger;
            $.ajax({
                type: "PUT",
                url: `https://localhost:44373/api/Category/UpdateSubCategory?Id=${subCatId}&SubCategoryName=${subCatName}`,
                success: function (result) {
                    console.log("SubCatEditted");
                    window.location.href = "/Shared/EditSubCategory"
                },
                error: function (result) {
                    console.log(result);
                }

            });
        });
    });
</script>

Views/Shared/GetSubCategory.cshtml
<table class="table">
    <thead>
        <tr>
            <th>Subcategory</th>            
        </tr>
    </thead>
    <tbody>
        @{
            foreach (var item in ViewBag.SubcategoryList)
            {
                <tr>
                    <td>@item.SubCategoryName</td>
                   
                
                    <td><a class="btn btn-warning"  asp-controller="Shared" asp-action="EditSubCategory" asp-route-id="@item.SubCategoryId">Edit</a></td>
                    <td><button type"button" sub-cat-id="@item.SubCategoryId" class="btn btn-danger subDelete">Delete</button></td>
                </tr>
            }
        }
        
    </tbody>
</table>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="~/js/index.js" ></script>
<script>

    $(".subDelete").click(function () {
        debugger;
        var categoryId = $(this).attr('sub-cat-id');

        console.log(categoryId)


        debugger;
        $.ajax({
            type: "DELETE",
            url: `https://localhost:44373/api/Category/DeleteSubCategory?id=${categoryId}`,


            success: function (response) {
                if (response) {
                    window.location.href = "/Shared/AllCategories";

                }

            },
            error: function (response) {

            }
        })
    })

</script>

Views/Shared/_Layout.cshtml
@using Newtonsoft.Json
@using System.Net.Http.Headers
@{


    var Client = new HttpClient();
    var apiUrl = "https://localhost:44373/api/Category/GetAllCategory";
    var token = GlobalVariable.Token;
    Client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
    Client.DefaultRequestHeaders.Add("X-UserRole", GlobalVariable.Role);
    var response = await Client.GetAsync(apiUrl);
    var data = JsonConvert.DeserializeObject<List<Categories>>(await response.Content.ReadAsStringAsync());
}

<html lang="en">
<head>
    <!-- basic -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- mobile metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <!-- site metas -->
    <title>Pluto - Responsive Bootstrap Admin Panel Templates</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- bootstrap css -->
    <link rel="stylesheet" href="~/css/bootstrap.min.css" />
    <!-- site css -->
    <link rel="stylesheet" href="~/css/style.css" />
    <!-- responsive css -->
    <link rel="stylesheet" href="~/css/responsive.css" />
    <!-- select bootstrap -->
    <link rel="stylesheet" href="~/css/bootstrap-select.css" />
    <!-- scrollbar css -->
    <link rel="stylesheet" href="~/css/perfect-scrollbar.css" />
    <!-- custom css -->
    <link rel="stylesheet" href="~/css/custom.css" />

</head>
<body class="dashboard dashboard_1">

    <div class="full_container">
        <div class="inner_container">
            <!-- Sidebar  -->
            <nav id="sidebar">
                <div class="sidebar_blog_1">
                    <div class="sidebar-header">
                        <div class="logo_section">
                            @*  <a href="index.html"><img class="logo_icon img-responsive" src="images/logo/logo_icon.png" alt="#" /></a> *@
                        </div>
                    </div>
                    <div class="sidebar_user_info">
                        <div class="icon_setting"></div>

                    </div>
                    <div class="sidebar_blog_2">
                        <h4>My Categoryies</h4> 
                        <a class="btn btn-dark" asp-action="CartIndex" asp-controller="Cart">Cart </a>


                        <ul class="list-unstyled components">

                            <li>
                                @foreach (var item in data)
                                {
                                    <a href="#@($"{item.CategoryId}")" category-id="@item.CategoryId" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle CategoryId">
                                        <i class="fa fa-diamond purple_color"></i> <span>@item.CategoryName  </span>

                                    </a>


                                    <ul class="collapse list-unstyled" id="@($"{item.CategoryId}")">
                                        @foreach (var sub in item.SubCategoryList)
                                        {
                                            <li><a href="" class="subCategoryName" value="@sub.SubCategoryId"> <span>@sub.SubCategoryName</span></a> </li>
                                            //  <input type="hidden" value="@sub.SubCategoryId" id="subCategoryId"/>
                                        }
                                    </ul>
                                }
                            </li>
                        </ul>
                    </div>
            </nav>
            <!-- end sidebar -->
            <!-- right content -->
            <div id="content">
                @RenderBody()
             
                <!-- topbar -->
                <div class="topbar">
                    <nav class="navbar navbar-expand-lg navbar-light">
                        <div class="full">
                            <button type="button" id="sidebarCollapse" class="sidebar_toggle"><i class="fa fa-bars"></i></button>
                            <div class="logo_section">
                                @* <a href="index.html"><img class="img-responsive" src="~/images/logo/logo.png" alt="#" /></a> *@
                            </div>
                            <div class="right_topbar">
                                <div class="icon_info">

                                    <ul class="user_profile_dd">
                                        <li>
                                            <a class="dropdown-toggle" data-toggle="dropdown"><img class="img-responsive rounded-circle" src="~/images/layout_img/user_img.jpg" alt="#" /><span class="name_user">Management</span></a>
                                            <div class="dropdown-menu">
                                                <a class="btn btn-secondary dropdown-item" asp-controller="Home" asp-action="Login">Login</a>
                                                <div class="dropdown-divider"></div>
                                                <a class="btn btn-secondary dropdown-item" asp-controller="Home" asp-action="Logout">Log Out</a>
                                                <div class="dropdown-divider"></div>
                                                <a class="btn btn-secondary dropdown-item" asp-controller="Shared" asp-action="AddCategory">Add Category</a>
                                                <div class="dropdown-divider"></div>
                                                <a class="btn btn-secondary dropdown-item" asp-controller="Shared" asp-action="AllCategories">Show Categories</a>
                                                <div class="dropdown-divider"></div>
                                                <a class="btn btn-secondary dropdown-item" asp-controller="Shared" asp-action="Add">Add Subcategory</a>
                                                <div class="dropdown-divider"></div>
                                                <a class="btn btn-secondary dropdown-item" asp-controller="ProductView" asp-action="AddProduct">Add Product</a>
                                                <div class="dropdown-divider"></div>
                                                <a class="btn btn-secondary dropdown-item" asp-controller="ProductView" asp-action="ShowProducts">Product List</a>
                                                <div class="dropdown-divider"></div>
                                                <a class="btn btn-secondary dropdown-item" asp-controller="Home" asp-action="Index">Home Page</a>
                                            </div>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </nav>
                </div>
                <!-- end topbar -->
                <!-- dashboard inner -->

            </div>
        </div>
    </div>
    <!-- jQuery -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <!-- wow animation -->
    <script src="~/js/animate.js"></script>
    <!-- select country -->
    <script src="~/js/bootstrap-select.js"></script>
    <!-- owl carousel -->
    <script src="~/js/owl.carousel.js"></script>

    <script src="~/js/popper.min.js"></script>

    <!-- custom js -->
    <script src="~/js/custom.js"></script>
    <script src="~/js/index.js"></script>
    <script>

            $(document).ready(function () {
            $("#Products").on("click", ".productImage", function () {
                var productId = $(this).attr("productid");
                 window.location.href = "/ProductView/ProductDetail/" + productId;
               
              
            });
            //method for redirectind to product details

            $(".subCategoryName").click(function () {
                event.preventDefault();
                var subCategoryId = $(this).attr('value');
                console.log(subCategoryId);
                $("#Products").empty();
                $.ajax({
                    method: "GET",
                    url: "https://localhost:44373/api/Product/GetProductBySubCategoryId",
                    data: { id: subCategoryId },
                    success: function (data) {
                        console.log(data);
                        for (var i = 0; i < data.length; i++) {
                            var product = data[i];
                            var productHtml = `
                                <div class="card" style="width: 18rem;">
                                <img src="/images/${product.productImage}" alt="Not Found" class="card-img-top productImage" productid="${product.productId}">
                                <h4 class="card-title">${product.productPrice} Rs</h4>
                                    <div class="card-body">
                                        <h5 class="card-title">${product.productName}</h5>                                        
                                    </div>
                                </div> `;
                            $("#Products").append(productHtml);
                        }

                    }
                });
            });

        });
    </script>

</body>
</html>